import {StyleSheet} from 'react-native'; 
//https://css-tricks.com/snippets/css/a-guide-to-flexbox/
const theme = StyleSheet.create({
    label:{
        // marginTop:10,
        fontWeight:'bold',
        marginLeft:'10%'
    },
    ansewr:{
        marginLeft:'40%',
        marginVertical:'auto',
    },
    border:{
        borderBottomWidth:1
    },
    userTile:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between',
        borderWidth:1,
        borderColor:'#000',
        padding:5,
        margin:5,
        marginHorizontal:50
    },
    userTileButtonContainer:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between',
        
    },
    userTileButton:{
        backgroundColor:'green',
        padding:5,
        marginLeft:2.5,
        minWidth:55,
        
    },
    userTileButtonText:{
        color:'#fff',
        textAlign:'center'
    },
    detailTitle:{
        borderWidth:1,
        marginBottom:10
    },
    addContactButton:{
        backgroundColor:'green',
        padding:5,
        borderRadius:1000,
        width:50,
        alignSelf:'flex-end',
        margin:'3%'
    },
    addContactButtonText:{
        color:'#fff',
        textAlign:'center'
    },
    deleteContactButton:{
        backgroundColor:'red',
        padding:5,
        marginTop:10,
        maxWidth:75,
        width:'15%',
        marginHorizontal:'auto'
    },
    deleteContactButtonText:{
        color:'#fff',
        textAlign:'center'
    },
    saveButton:{
        backgroundColor:'gray',
        padding:5,
        marginTop:5,
        marginLeft:5,
        width:'15%',
        alignSelf:'flex-end',
        marginRight:'10%',
        borderRadius:10,
    },
    saveButtonText:{
        color:'#fff',
        textAlign:'center'
    },
    cancelButton:{
        backgroundColor:'red',
        padding:5,
        marginTop:5
    },
    cancelButtonText:{
        color:'#fff',
        textAlign:'center'
    },  
    textInput:{
        backgroundColor:'#fff',
        borderColor:'#000',
        borderWidth:1,
        margin:2.5,
        padding:2.5,
        marginHorizontal:'10%'
    }
}); 

export default theme; 